spring.application.name=Peliculas

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/peliculasdb
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración del servidor
server.port=8083
# Configuración del cliente web
autenticacion.service.url=http://localhost:8083